
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: my-rabbit
    hostname: my-rabbit
    ports:
      - "15672:15672"  # Management interface
      - "5672:5672"    # AMQP
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      # Add these to increase header size limits
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}] -rabbit server_request_timeout 60000
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_data: